version: '3.8'
services:
  toply:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Toply
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
